# This script performs differential expression analysis on the data generated by earlier scripts by using the DESeq2 package. 
# This script will also generate a table of the 15 most significant genes in LaTeX format, and a volcano plot in pdf format.
# Note: This script should be run from the "Results" directory
rm(list = ls()); dev.off(); graphics.off()

#---------- get the data (to keep from running the other scripts)
# URL1<- "https://raw.githubusercontent.com/davidgllund/BBT015_Project/master/Intermediate/countMatrix.tsv"
# URL2<- "https://raw.githubusercontent.com/davidgllund/BBT015_Project/master/Intermediate/geneNames.tsv"
# download.file(URL1, "countMatrix.tsv")
# download.file(URL2, "geneNames.tsv")
#---------- Organize Matrix
CountMatrix<-read.table("../Intermediate/countMatrix.tsv")
GeneNames <-read.table("../Intermediate/geneNames.tsv")
rownames(CountMatrix)<- t(GeneNames)

Condition <-c('control','control','control','knockout','knockout','knockout') # sample conditions as a vector
coldata <-as.data.frame(Condition) # Because DESeqDataSetFromMatrix() wants it as a data frame

#---------------Make DESeq data frame
library("DESeq2")
DESeqData<-DESeqDataSetFromMatrix(CountMatrix, coldata, ~ Condition)

#---------------filter
dds <- DESeqData[rowSums(counts(DESeqData)) >=10,] #keep genes with more counts than 10 (can be adjusted or removed)

#--------------- Run DESeq
dds <- DESeq(dds,test="Wald") # test=wald because that was specified in the article
res <- results(dds) 

#-------------- Extract the relevant stuff
#Build vector of adjusted p-value, log fold change and rownames (gene names)
padj=as.vector(res$padj)
names=as.vector(rownames(res)) #put names in a vector
LFC=as.vector(res$log2FoldChange)
#Create pretty matrix
Results=cbind(LFC,padj)
rownames(Results)<- names
colnames(Results)<- c('LFC', 'Padj')

#Filter to exclude NA (if present) and high p-values (article used 0.05 as cut-off)
Results=Results[!is.na(padj) & Results[,2]<0.05,]

#Sort by increasing p-values
Results.sorted=Results[order((Results[,2])),]
View(Results.sorted)

#Upregulated vs downregulated
LFC.Down=Results.sorted[Results.sorted[,1]<0,]
LFC.UP=Results.sorted[!Results.sorted[,1]<0,]

# Generate table of top 15 most significant genes in LaTeX format
library("xtable")
top15 <- Results.sorted[1:15,]
xtable(top15)

# -----------------------------------------------------
# Visualization
# -----------------------------------------------------
# Load ggplot2 library
library("ggplot2")

# Convert 'Results' matrix to data.frame
Results <- as.data.frame(Results)

# Set threshold for p-values and log fold change
Results$threshold <- as.factor(abs(Results$LFC) > 2 & Results$Padj < 0.05)

# Generate volcano plot and export to the "Figures" subdirectory
pdf(file = "Figures/Vocano_plot.pdf")

ggplot(data = Results, aes(x = LFC, y = -log10(Padj), colour = threshold)) +
  geom_point(alpha=0.6, size=1.75) +
  scale_color_manual(values = c(1, 3)) +
  theme(legend.position="none") +
  xlim(c(-6,6)) + ylim(c(0,125)) +
  xlab("log2 fold change") + ylab("-log10 P-value adj") +
  ggtitle("ppx2 knockdown vs Empty vector") + theme(plot.title = element_text(hjust=0.5))

dev.off()






